### ISSUE TITLE
Message with (invalid) length 251

### ISSUE THREAD

**Issue by denPaco** [hpsaturn/ESPNowCam#45]
Hi @hpsaturn , 

I am using the library to send every 5 sec a picture following the example code provided, using a ESP32-CAM.
From time to time, the program hangs and I get following error:

E (3537447) ESPNOW: Invalid argument!

I added a log_e to print the message length:

  } else if (result == ESP_ERR_ESPNOW_ARG) {
    log_e("Invalid Argument");
    log_e("Message length: %d", msglen);

With result:
[3537453][E][ESPNowCam.cpp:88] sendMessage(): Invalid Argument
[3537560][E][ESPNowCam.cpp:89] sendMessage(): Message length: 251

Only happens occasionally.
My workaround right now is to restart with ESP.restart in case this happens.

**Comment by hpsaturn** [comment]
Thanks for your feedback and comments. Well, I think that maybe these kind of messages are more for lost transmissions, or when these transmissions overlapping other radios. Did you test the p2p option? of course if you are using only one transmitter and one receptor.

**Comment by hpsaturn** [comment]
For now, I'm going to close this stale issue
